<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="NodaTime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingPlatform.Platform\TradingPlatform.Platform.csproj" />
  </ItemGroup>
</Project>
